### PR TITLE
Update owners file

### PR DESCRIPTION
**Pull request by son-vyas**

### CODE REVIEW

**Review by pojadhav — APPROVED** [review]

**Comment by sdatko** [comment]
LGTM :ok_hand:

**Comment by frenzyfriday** [comment]
/lgtm

Just to be sure, you are removing Arx? Just making sure that is not a typo 😅

**Comment by son-vyas** [comment]
> /lgtm
> 
> Just to be sure, you are removing Arx? Just making sure that is not a typo 😅

yeah, it is not a typo

**Review by lpiwowar — APPROVED** [review]
Looks good to me!

**Pull request merged**
