### PR TITLE
  Fixing black lint issues

### PR DESCRIPTION
**Pull request by son-vyas**
Fixing black lint issues
Depends-On:  https://github.com/openstack-k8s-operators/openstack-tests-list/pull/17

### CODE REVIEW

**Review by kopecmartin — CHANGES_REQUESTED** [review]
this fixes the pre-commit falures, however, the pre-commit action doesn't take this change into account, it clones the repo but doesn't cherry-pick the new changes = thus we're testing the already merged code, not the code that is about to be merged.

https://github.com/openstack-k8s-operators/openstack-tests-list/blob/main/.github/workflows/ci.yaml#L38
here we only clone, we don't checkout the latest change

**Comment by son-vyas** [comment]
recheck

**Comment by kopecmartin** [comment]
recheck

**Comment by kopecmartin** [comment]
seems like this needs to be rebased

**Comment by son-vyas** [comment]
recheck

**Review by kopecmartin — APPROVED** [review]

**Pull request merged**
